[package]
org = "wso2"
name = "Hl7v2ToFhirR4Service"
version = "1.1.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","HL7V2", "Transform"]

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.hl7v2.utils.v2tofhirr4"
version = "2.2.0"
