openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 1.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /transform:
    post:
      operationId: postTransform
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: InternalServerError
          content:
            text/plain:
              schema:
                type: string
components: {}
